use std::fs;
use std::io::{BufRead, BufReader};
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

use super::{get_claude_dir, guard_path_within_home, validate_path_component, JsonlEntry, Project, Session};

#[cfg(target_os = "windows")]
use super::project_wsl;

/// Gets the actual project path by reading the cwd from the JSONL entries
pub(super) fn get_project_path_from_sessions(
    project_dir: &PathBuf,
) -> Result<String, String> {
    let entries = fs::read_dir(project_dir)
        .map_err(|e| format!("Failed to read project directory: {}", e))?;

    for entry in entries {
        if let Ok(entry) = entry {
            let path = entry.path();
            if path.is_file() && path.extension().and_then(|s| s.to_str()) == Some("jsonl") {
                if let Ok(file) = fs::File::open(&path) {
                    let reader = BufReader::new(file);
                    // Check first few lines — some session files may have null cwd in the first line.
                    for line in reader.lines().take(10) {
                        if let Ok(line_content) = line {
                            if let Ok(json) =
                                serde_json::from_str::<serde_json::Value>(&line_content)
                            {
                                if let Some(cwd) = json.get("cwd").and_then(|v| v.as_str()) {
                                    if !cwd.is_empty() {
                                        return Ok(cwd.to_string());
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    Err("Could not determine project path from session files".to_string())
}

/// Decodes a project directory name back to its original path.
/// DEPRECATED: Use get_project_path_from_sessions instead when possible.
pub(super) fn decode_project_path(encoded: &str) -> String {
    encoded.replace('-', "/")
}

/// Extracts the first valid user message from a JSONL file
pub(super) fn extract_first_user_message(
    jsonl_path: &PathBuf,
) -> (Option<String>, Option<String>) {
    let file = match fs::File::open(jsonl_path) {
        Ok(file) => file,
        Err(_) => return (None, None),
    };

    let reader = BufReader::new(file);

    for line in reader.lines() {
        if let Ok(line) = line {
            if let Ok(entry) = serde_json::from_str::<JsonlEntry>(&line) {
                if let Some(message) = entry.message {
                    if message.role.as_deref() == Some("user") {
                        if let Some(content) = message.content {
                            if content.contains("Caveat: The messages below were generated by the user while running local commands") {
                                continue;
                            }
                            if content.starts_with("<command-name>")
                                || content.starts_with("<local-command-stdout>")
                            {
                                continue;
                            }
                            return (Some(content), entry.timestamp);
                        }
                    }
                }
            }
        }
    }

    (None, None)
}

/// Gets the user's home directory path.
/// When `wsl_distro` is provided (Windows only), retrieves the home directory
/// from inside the specified WSL distribution instead of the native Windows home.
#[tauri::command]
pub async fn get_home_directory(wsl_distro: Option<String>) -> Result<String, String> {
    #[cfg(target_os = "windows")]
    if let Some(ref distro) = wsl_distro {
        if !distro.is_empty() {
            return get_home_directory_wsl(distro).await;
        }
    }
    let _ = wsl_distro; // suppress unused warning on non-Windows
    dirs::home_dir()
        .and_then(|path| path.to_str().map(|s| s.to_string()))
        .ok_or_else(|| "Could not determine home directory".to_string())
}

/// Retrieves the home directory from inside a WSL distribution.
#[cfg(target_os = "windows")]
async fn get_home_directory_wsl(distro: &str) -> Result<String, String> {
    let d = distro.to_string();
    tokio::task::spawn_blocking(move || {
        let output = crate::claude_binary::silent_command("wsl")
            .args(["-d", &d, "--", "bash", "-lc", "echo $HOME"])
            .output()
            .map_err(|e| format!("WSL home dir: {}", e))?;
        let home = String::from_utf8_lossy(&output.stdout).trim().to_string();
        if home.is_empty() {
            Err("Could not determine WSL home directory".to_string())
        } else {
            Ok(home)
        }
    })
    .await
    .map_err(|e| e.to_string())?
}

/// Lists all projects in the ~/.claude/projects directory.
/// When `wsl_distro` is provided (Windows only), reads projects from inside the
/// specified WSL distribution rather than from the native Windows filesystem.
#[tauri::command]
pub async fn list_projects(wsl_distro: Option<String>) -> Result<Vec<Project>, String> {
    log::info!("Listing projects from ~/.claude/projects");

    #[cfg(target_os = "windows")]
    if let Some(ref distro) = wsl_distro {
        if !distro.is_empty() {
            return project_wsl::list_projects_wsl(distro).await;
        }
    }
    let _ = wsl_distro; // suppress unused warning on non-Windows

    let claude_dir = get_claude_dir().map_err(|e| e.to_string())?;
    let projects_dir = claude_dir.join("projects");

    if !projects_dir.exists() {
        log::warn!("Projects directory does not exist: {:?}", projects_dir);
        return Ok(Vec::new());
    }

    tokio::task::spawn_blocking(move || {
        let mut projects = Vec::new();

        let entries = fs::read_dir(&projects_dir)
            .map_err(|e| format!("Failed to read projects directory: {}", e))?;

        for entry in entries {
            let entry =
                entry.map_err(|e| format!("Failed to read directory entry: {}", e))?;
            let path = entry.path();

            if path.is_dir() {
                let dir_name = path
                    .file_name()
                    .and_then(|n| n.to_str())
                    .ok_or_else(|| "Invalid directory name".to_string())?;

                let metadata = fs::metadata(&path)
                    .map_err(|e| format!("Failed to read directory metadata: {}", e))?;

                let created_at = metadata
                    .created()
                    .or_else(|_| metadata.modified())
                    .unwrap_or(SystemTime::UNIX_EPOCH)
                    .duration_since(SystemTime::UNIX_EPOCH)
                    .unwrap_or_default()
                    .as_secs();

                let project_path = match get_project_path_from_sessions(&path) {
                    Ok(path) => path,
                    Err(e) => {
                        log::warn!(
                            "Failed to get project path from sessions for {}: {}, falling back to decode",
                            dir_name,
                            e
                        );
                        decode_project_path(dir_name)
                    }
                };

                let mut sessions = Vec::new();
                let mut most_recent_session: Option<u64> = None;

                if let Ok(session_entries) = fs::read_dir(&path) {
                    for session_entry in session_entries.flatten() {
                        let session_path = session_entry.path();
                        if session_path.is_file()
                            && session_path.extension().and_then(|s| s.to_str())
                                == Some("jsonl")
                        {
                            if let Some(session_id) =
                                session_path.file_stem().and_then(|s| s.to_str())
                            {
                                sessions.push(session_id.to_string());

                                if let Ok(metadata) = fs::metadata(&session_path) {
                                    let modified = metadata
                                        .modified()
                                        .unwrap_or(SystemTime::UNIX_EPOCH)
                                        .duration_since(UNIX_EPOCH)
                                        .unwrap_or_default()
                                        .as_secs();

                                    most_recent_session = Some(match most_recent_session {
                                        Some(current) => current.max(modified),
                                        None => modified,
                                    });
                                }
                            }
                        }
                    }
                }

                projects.push(Project {
                    id: dir_name.to_string(),
                    path: project_path,
                    sessions,
                    created_at,
                    most_recent_session,
                });
            }
        }

        projects.sort_by(|a, b| match (a.most_recent_session, b.most_recent_session) {
            (Some(a_time), Some(b_time)) => b_time.cmp(&a_time),
            (Some(_), None) => std::cmp::Ordering::Less,
            (None, Some(_)) => std::cmp::Ordering::Greater,
            (None, None) => b.created_at.cmp(&a.created_at),
        });

        log::info!("Found {} projects", projects.len());
        Ok(projects)
    })
    .await
    .map_err(|e| e.to_string())?
}

/// Creates a new project for the given directory path
#[tauri::command]
pub async fn create_project(path: String) -> Result<Project, String> {
    log::info!("Creating project for path: {}", path);

    guard_path_within_home(&PathBuf::from(&path))?;

    let project_id = path.replace('/', "-");

    let claude_dir = get_claude_dir().map_err(|e| e.to_string())?;
    let projects_dir = claude_dir.join("projects");

    if !projects_dir.exists() {
        fs::create_dir_all(&projects_dir)
            .map_err(|e| format!("Failed to create projects directory: {}", e))?;
    }

    let project_dir = projects_dir.join(&project_id);
    if !project_dir.exists() {
        fs::create_dir_all(&project_dir)
            .map_err(|e| format!("Failed to create project directory: {}", e))?;
    }

    let metadata = fs::metadata(&project_dir)
        .map_err(|e| format!("Failed to read directory metadata: {}", e))?;

    let created_at = metadata
        .created()
        .or_else(|_| metadata.modified())
        .unwrap_or(SystemTime::UNIX_EPOCH)
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();

    Ok(Project {
        id: project_id,
        path,
        sessions: Vec::new(),
        created_at,
        most_recent_session: None,
    })
}

/// Gets sessions for a specific project.
/// When `wsl_distro` is provided (Windows only), reads session data from inside
/// the specified WSL distribution.
#[tauri::command]
pub async fn get_project_sessions(
    project_id: String,
    wsl_distro: Option<String>,
) -> Result<Vec<Session>, String> {
    log::info!("Getting sessions for project: {}", project_id);

    validate_path_component(&project_id, "project_id")?;

    #[cfg(target_os = "windows")]
    if let Some(ref distro) = wsl_distro {
        if !distro.is_empty() {
            return project_wsl::get_project_sessions_wsl(&project_id, distro).await;
        }
    }
    let _ = wsl_distro; // suppress unused warning on non-Windows

    let claude_dir = get_claude_dir().map_err(|e| e.to_string())?;
    let project_dir = claude_dir.join("projects").join(&project_id);
    let todos_dir = claude_dir.join("todos");

    if !project_dir.exists() {
        return Err(format!("Project directory not found: {}", project_id));
    }

    tokio::task::spawn_blocking(move || {
        let project_path = match get_project_path_from_sessions(&project_dir) {
            Ok(path) => path,
            Err(e) => {
                log::warn!(
                    "Failed to get project path from sessions for {}: {}, falling back to decode",
                    project_id,
                    e
                );
                decode_project_path(&project_id)
            }
        };

        let mut sessions = Vec::new();

        let entries = fs::read_dir(&project_dir)
            .map_err(|e| format!("Failed to read project directory: {}", e))?;

        for entry in entries {
            let entry =
                entry.map_err(|e| format!("Failed to read directory entry: {}", e))?;
            let path = entry.path();

            if path.is_file() && path.extension().and_then(|s| s.to_str()) == Some("jsonl") {
                if let Some(session_id) = path.file_stem().and_then(|s| s.to_str()) {
                    let metadata = fs::metadata(&path)
                        .map_err(|e| format!("Failed to read file metadata: {}", e))?;

                    let created_at = metadata
                        .created()
                        .or_else(|_| metadata.modified())
                        .unwrap_or(SystemTime::UNIX_EPOCH)
                        .duration_since(SystemTime::UNIX_EPOCH)
                        .unwrap_or_default()
                        .as_secs();

                    let (first_message, message_timestamp) =
                        extract_first_user_message(&path);

                    let todo_path = todos_dir.join(format!("{}.json", session_id));
                    let todo_data = if todo_path.exists() {
                        fs::read_to_string(&todo_path)
                            .ok()
                            .and_then(|content| serde_json::from_str(&content).ok())
                    } else {
                        None
                    };

                    sessions.push(Session {
                        id: session_id.to_string(),
                        project_id: project_id.clone(),
                        project_path: project_path.clone(),
                        todo_data,
                        created_at,
                        first_message,
                        message_timestamp,
                    });
                }
            }
        }

        sessions.sort_by(|a, b| b.created_at.cmp(&a.created_at));

        log::info!(
            "Found {} sessions for project {}",
            sessions.len(),
            project_id
        );
        Ok(sessions)
    })
    .await
    .map_err(|e| e.to_string())?
}
